name:               haspara-accounting
version:            0.0.0.0
github:             "telostat/haspara-accounting"
license:            MIT
author:             "Vehbi Sinan Tunalioglu"
maintainer:         "vst@vsthost.com"
copyright:          "Copyright (c) 2021 Telostat Pte Ltd"

description:        Please see the README on GitHub at <https://github.com/telostat/haspara-accounting#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.11 && < 5
- aeson
- deriving-aeson
- hashable
- haspara
- mtl
- refined
- text

library:
  source-dirs:      src
  ghc-options:
  - -Wall
  default-extensions:
  - OverloadedStrings

tests:
  haspara-accounting-doctest:
    main:           doctest.hs
    source-dirs:    test
    ghc-options:
    - -threaded
    dependencies:
    - haspara-accounting
    - doctest
